# Generated by Django 3.2.9 on 2022-04-19 14:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name="Car's brand")),
                ('model', models.CharField(max_length=50, verbose_name="Car's model")),
                ('fuel_type', models.CharField(choices=[('GSL', 'Gasoline'), ('DSL', 'Diesel'), ('GAS', 'Gas'), ('ELC', 'Electric')], max_length=50, verbose_name="Car's fuel type")),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2022)], verbose_name='Year of issue.')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name="Car's price($)")),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.image')),
            ],
        ),
    ]
