# Generated by Django 3.2.9 on 2022-04-20 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_create_car_and_image_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2022)], verbose_name='Year of issue'),
        ),
    ]
