# Generated by Django 3.2.9 on 2022-04-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_create_car_and_image_models'),
        ('customer', '0001_create_customer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
    ]
