# Generated by Django 3.2.9 on 2022-04-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_change_customer_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Current balance in $'),
        ),
    ]
