# Generated by Django 3.2.9 on 2022-04-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_change_car_model'),
        ('customer', '0005_alter_customer_pref_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
    ]
