# Generated by Django 3.2.9 on 2022-04-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0002_change_dealership_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Current balance in $'),
        ),
    ]
