# Generated by Django 3.2.9 on 2022-04-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_change_car_model'),
        ('dealership', '0003_edit_dealership_balance_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='pref_cars',
            field=models.JSONField(default='{"price": ,"brand": ,"model": ,"fuel_type": ,"year": }'),
        ),
        migrations.CreateModel(
            name='DealershipSoldCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Sold price')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('dealership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.dealership')),
            ],
        ),
    ]
