# Generated by Django 3.2.9 on 2022-04-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0004_change_dealership_model_add_soldcars_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='pref_cars',
            field=models.JSONField(default={'brand': '', 'fuel_type': '', 'model': '', 'price': '', 'year': ''}),
        ),
    ]
